export const LIVE_SCENARIO = {
  id: "SMARTBOX_COLD_CHAIN_HANOI_DANANG_V1",
  name: "Cold Chain Delivery: Hà Nội → Đà Nẵng",
  totalDuration: 120,
  description:
    "Mô phỏng vận chuyển dược phẩm lạnh bằng SmartBox IoT, có QR tracking, cảm biến, GPS, cảnh báo nhiệt độ và xử lý sự cố.",
};

export const LIVE_SMARTBOXES = [
  {
    id: "live-box-001",
    box_id: "SBX-LIVE-001",
    box_name: "Cold Chain Box 001",
    status: "Sẵn sàng",
    current_order_id: null,
    last_latitude: 21.0285,
    last_longitude: 105.8542,
    last_temperature: 4.6,
    last_humidity: 61,
    last_shock: 0.06,
    battery_level: 98,
    firmware_version: "v1.5.0",
    last_seen: null,
    live_generated: true,
  },
  {
    id: "live-box-002",
    box_id: "SBX-LIVE-002",
    box_name: "Fresh Food Box 002",
    status: "Sẵn sàng",
    current_order_id: null,
    last_latitude: 10.8231,
    last_longitude: 106.6297,
    last_temperature: -18.4,
    last_humidity: 48,
    last_shock: 0.04,
    battery_level: 91,
    firmware_version: "v1.5.0",
    last_seen: null,
    live_generated: true,
  },
  {
    id: "live-box-003",
    box_id: "SBX-LIVE-003",
    box_name: "Fragile Goods Box 003",
    status: "Bảo trì",
    current_order_id: null,
    last_latitude: 16.0544,
    last_longitude: 108.2022,
    last_temperature: 27.2,
    last_humidity: 58,
    last_shock: 0.3,
    battery_level: 43,
    firmware_version: "v1.3.8",
    last_seen: null,
    live_generated: true,
  },
];

export const LIVE_ORDERS = [
  {
    id: "live-order-001",
    order_code: "ORD-LIVE-001",
    sender_name: "Công ty Dược phẩm An Tâm",
    receiver_name: "Bệnh viện Đà Nẵng",
    origin: "Kho lạnh Long Biên, Hà Nội",
    destination: "Bệnh viện Đà Nẵng",
    cargo_type: "Dược phẩm lạnh",
    status: "Chờ xử lý",
    smartbox_id: "SBX-LIVE-001",
    estimated_delivery: "2026-05-05",
    notes:
      "Yêu cầu duy trì nhiệt độ 2°C - 8°C. Hệ thống Live sẽ tự sinh cảm biến, GPS, cảnh báo và cập nhật trạng thái.",
    live_generated: true,
  },
  {
    id: "live-order-002",
    order_code: "ORD-LIVE-002",
    sender_name: "Hải sản Minh Phú",
    receiver_name: "Siêu thị Cần Thơ",
    origin: "Cảng Cát Lái, TP.HCM",
    destination: "Ninh Kiều, Cần Thơ",
    cargo_type: "Thực phẩm đông lạnh",
    status: "Chờ xử lý",
    smartbox_id: "SBX-LIVE-002",
    estimated_delivery: "2026-05-05",
    notes: "Duy trì nhiệt độ âm sâu trong suốt quá trình vận chuyển.",
    live_generated: true,
  },
  {
    id: "live-order-003",
    order_code: "ORD-LIVE-003",
    sender_name: "TechCare Việt Nam",
    receiver_name: "Trung tâm bảo hành Huế",
    origin: "KCN Hòa Khánh, Đà Nẵng",
    destination: "TP. Huế",
    cargo_type: "Linh kiện điện tử dễ vỡ",
    status: "Chờ xử lý",
    smartbox_id: null,
    estimated_delivery: "2026-05-06",
    notes: "Cần giám sát va chạm và độ ẩm, chờ SmartBox sau bảo trì.",
    live_generated: true,
  },
];

const route = [
  { second: 15, lat: 21.0285, lng: 105.8542, place: "Hà Nội", temp: 4.6, humidity: 61, shock: 0.06, battery: 98, open: false },
  { second: 25, lat: 20.2506, lng: 105.9745, place: "Ninh Bình", temp: 5.1, humidity: 62, shock: 0.08, battery: 96, open: false },
  { second: 35, lat: 19.8075, lng: 105.7764, place: "Thanh Hóa", temp: 6.7, humidity: 63, shock: 0.11, battery: 94, open: false },
  { second: 45, lat: 18.6796, lng: 105.6813, place: "Nghệ An", temp: 9.2, humidity: 66, shock: 0.15, battery: 91, open: false },
  { second: 55, lat: 18.6796, lng: 105.6813, place: "Trạm xử lý Nghệ An", temp: 7.4, humidity: 64, shock: 0.1, battery: 89, open: true },
  { second: 70, lat: 17.4689, lng: 106.6223, place: "Quảng Bình", temp: 5.8, humidity: 63, shock: 1.2, battery: 86, open: false },
  { second: 90, lat: 16.4637, lng: 107.5909, place: "Huế", temp: 4.9, humidity: 61, shock: 0.09, battery: 82, open: false },
  { second: 110, lat: 16.0544, lng: 108.2022, place: "Đà Nẵng", temp: 4.7, humidity: 60, shock: 0.05, battery: 79, open: false },
];

const sensorEvents = route.map((point, index) => ({
  id: `evt_sensor_${String(index + 1).padStart(2, "0")}`,
  at: point.second,
  type: "sensor_reading",
  payload: {
    id: `live-sensor-${String(index + 1).padStart(2, "0")}`,
    smartbox_id: "SBX-LIVE-001",
    order_id: "live-order-001",
    temperature: point.temp,
    humidity: point.humidity,
    shock_g: point.shock,
    latitude: point.lat,
    longitude: point.lng,
    battery: point.battery,
    is_open: point.open,
    place: point.place,
  },
  message: `SmartBox SBX-LIVE-001 gửi dữ liệu tại ${point.place}`,
}));

export const LIVE_TIMELINE = [
  {
    id: "evt_bootstrap",
    at: 0,
    type: "log",
    message: "Khởi tạo phiên Live Cold Chain Delivery",
  },
  {
    id: "evt_create_smartboxes",
    at: 2,
    type: "create_smartboxes",
    payload: LIVE_SMARTBOXES,
    message: "Tạo 3 SmartBox mẫu và đưa vào dữ liệu hệ thống",
  },
  {
    id: "evt_create_orders",
    at: 5,
    type: "create_orders",
    payload: LIVE_ORDERS,
    message: "Tạo 3 đơn hàng mẫu, bao gồm ORD-LIVE-001 có QR tracking",
  },
  {
    id: "evt_assign_cold_chain_box",
    at: 8,
    type: "update_smartbox",
    payload: {
      match: { box_id: "SBX-LIVE-001" },
      data: {
        status: "Đang vận chuyển",
        current_order_id: "live-order-001",
        last_seen: "NOW",
      },
    },
    message: "Gán SBX-LIVE-001 cho đơn ORD-LIVE-001",
  },
  {
    id: "evt_order_in_transit",
    at: 12,
    type: "update_order",
    payload: {
      match: { order_code: "ORD-LIVE-001" },
      data: { status: "Đang vận chuyển" },
    },
    message: "ORD-LIVE-001 bắt đầu vận chuyển từ Hà Nội",
  },
  ...sensorEvents,
  {
    id: "evt_temperature_alert",
    at: 46,
    type: "create_alert",
    payload: {
      id: "live-alert-temp-001",
      smartbox_id: "SBX-LIVE-001",
      order_id: "live-order-001",
      alert_type: "Nhiệt độ vượt ngưỡng",
      severity: "Cao",
      message: "Nhiệt độ tăng lên 9.2°C, vượt ngưỡng an toàn 8°C cho dược phẩm lạnh.",
      value: 9.2,
      threshold: 8,
      is_resolved: false,
      live_generated: true,
    },
    message: "Cảnh báo nhiệt độ vượt ngưỡng được tạo tự động",
    level: "warning",
  },
  {
    id: "evt_order_incident",
    at: 47,
    type: "update_order",
    payload: {
      match: { order_code: "ORD-LIVE-001" },
      data: { status: "Có sự cố" },
    },
    message: "ORD-LIVE-001 chuyển sang trạng thái Có sự cố",
    level: "warning",
  },
  {
    id: "evt_temperature_resolved",
    at: 58,
    type: "resolve_alert",
    payload: {
      match: { id: "live-alert-temp-001" },
      data: {
        is_resolved: true,
        resolved_at: "NOW",
        message: "Đã xử lý: nhân viên kiểm tra seal, khởi động lại module làm lạnh và nhiệt độ trở về mức an toàn.",
      },
    },
    message: "Cảnh báo nhiệt độ được xử lý, chuỗi lạnh ổn định trở lại",
  },
  {
    id: "evt_resume_transit_after_fix",
    at: 60,
    type: "update_order",
    payload: {
      match: { order_code: "ORD-LIVE-001" },
      data: { status: "Đang vận chuyển" },
    },
    message: "ORD-LIVE-001 tiếp tục vận chuyển sau khi xử lý sự cố",
  },
  {
    id: "evt_shock_alert",
    at: 72,
    type: "create_alert",
    payload: {
      id: "live-alert-shock-001",
      smartbox_id: "SBX-LIVE-001",
      order_id: "live-order-001",
      alert_type: "Va chạm nhẹ",
      severity: "Trung bình",
      message: "Cảm biến phát hiện va chạm 1.2G tại khu vực Quảng Bình. Chưa vượt ngưỡng khẩn cấp nhưng cần theo dõi.",
      value: 1.2,
      threshold: 1.5,
      is_resolved: true,
      resolved_at: "NOW",
      live_generated: true,
    },
    message: "Ghi nhận va chạm nhẹ và tự đánh dấu theo dõi",
    level: "warning",
  },
  {
    id: "evt_arriving_destination",
    at: 100,
    type: "log",
    message: "Xe vận chuyển vào khu vực Đà Nẵng, chuẩn bị bàn giao cho bệnh viện",
  },
  {
    id: "evt_delivered",
    at: 112,
    type: "update_order",
    payload: {
      match: { order_code: "ORD-LIVE-001" },
      data: { status: "Đã giao" },
    },
    message: "ORD-LIVE-001 đã giao thành công tại Bệnh viện Đà Nẵng",
  },
  {
    id: "evt_release_smartbox",
    at: 115,
    type: "update_smartbox",
    payload: {
      match: { box_id: "SBX-LIVE-001" },
      data: {
        status: "Sẵn sàng",
        current_order_id: null,
        last_temperature: 4.7,
        last_humidity: 60,
        last_shock: 0.05,
        battery_level: 79,
        last_latitude: 16.0544,
        last_longitude: 108.2022,
        last_seen: "NOW",
      },
    },
    message: "SBX-LIVE-001 được trả về trạng thái Sẵn sàng sau bàn giao",
  },
  {
    id: "evt_live_completed",
    at: 120,
    type: "complete",
    message: "Phiên Live hoàn tất và bị khóa để tránh chạy lại dữ liệu mẫu",
  },
].sort((a, b) => a.at - b.at);
